"kind/bug":
  - '^fix(\(.*\))?:.*'
"kind/cleanup":
  - '^chore(\(.*\))?:.*'
"kind/documentation":
  - '^docs(\(.*\))?:.*'
"kind/enhancement":
  - '^perf(\(.*\))?:.*'
"kind/feature":
  - '^feat(\(.*\))?:.*'
