"kind/bug":
  - '^[Ff]ix(\(.*\))?:?.*'
"kind/cleanup":
  - '^[Cc]hore(\(.*\))?:?.*'
"kind/documentation":
  - '^[Dd]ocs?(\(.*\))?:?.*'
"kind/enhancement":
  - '^[Pp]erf(\(.*\))?:?.*'
  - '^[Rr]efactor(\(.*\))?:?.*'
"kind/feature":
  - '^[Ff]eat(\(.*\))?:?.*'

